// D-13: Query 키는 여기서만 만든다. 사용자 범위 데이터는 userId를 키에 포함.
export const queryKeys = {
  me: (userId) => ['me', userId],
  gpsDraftsRoot: userId => ['gpsDrafts', userId],
  gpsDrafts: (userId, filters) => ['gpsDrafts', userId, 'list', filters],
  gpsDraft: (userId, id) => ['gpsDrafts', userId, 'detail', id],
  ownRoute: (userId, activityId) => ['activities', userId, 'route', activityId],
  postRoute: (userId, postId) => ['posts', userId, 'route', postId],
  memberRoot: (viewerId) => ['members', viewerId],
  member: (viewerId, memberId) => ['members', viewerId, memberId, 'profile'],
  memberRecords: (viewerId, memberId) => ['members', viewerId, memberId, 'records'],
  memberCrews: (viewerId, memberId) => ['members', viewerId, memberId, 'crews'],
  activities: (userId, filters = {}) => ['activities', userId, filters],
  activityList: (userId, filters) => ['activities', userId, 'list', filters],
  exerciseNames: (userId) => ['activities', userId, 'exerciseNames'],
  exerciseCatalog: (userId) => ['activities', userId, 'exerciseCatalog'],
  activity: (userId, activityId) => ['activities', userId, 'detail', activityId],
  meals: (userId, date) => ['meals', userId, date],
  mealList: (userId) => ['meals', userId, 'list'],
  meal: (userId, mealId) => ['meals', userId, 'detail', mealId],
  mealsRoot: (userId) => ['meals', userId],
  goals: (userId) => ['goals', userId],
  feedback: (userId, period, date) => ['feedback', userId, period, date],
  feedbackHistory: (userId) => ['feedbackHistory', userId],
  dashboard: (userId, period, date) => ['dashboard', userId, period, date],
  dashboardRoot: (userId) => ['dashboard', userId],
  activitiesRoot: (userId) => ['activities', userId],
  crews: (filters = {}) => ['crews', filters],
  crewListRoot: (userId) => ['crewList', userId],
  crewMatches: (userId) => ['crewList', userId, 'matches'],
  crewList: (userId, sport) => ['crewList', userId, sport],
  crewDetail: (userId, id) => ['crewDetail', userId, id],
  crewMembers: (userId, id) => ['crewMembers', userId, id],
  crewStats: (userId, id, period) => ['crewStats', userId, id, period],
  crewStatsRoot: (userId, id) => ['crewStats', userId, id],
  regions: (userId) => ['regions', userId],
  crew: (crewId) => ['crew', crewId],
  feed: (scope, crewId = null) => ['feed', scope, crewId],
  postsRoot: (userId) => ['posts', userId],
  postInteractionRoot: (userId,id) => ['posts',userId,'interactions',id],
  postInteraction: (userId,id,type) => ['posts',userId,'interactions',id,type],
  attachmentChoices: (userId) => ['attachmentChoices', userId],
  attachmentOwn: (userId, id) => ['attachmentOwn', userId, id],
  postAttachment: (userId, id) => ['posts', userId, 'attachment', id],
  postImages: (userId, paths) => ['posts', userId, 'images', paths],
  postList: (userId, crewId, kind) => ['posts', userId, 'list', crewId, kind],
  post: (userId, id) => ['posts', userId, 'detail', id],
  feedContext: (userId, crewId) => ['feedContext', userId, crewId],
  user: (userId) => ['user', userId],
};
