import {useRef,useState} from 'react';
import {Link} from 'react-router';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useAuth} from '../auth/index.js';
import {api} from '../../shared/api.js';
import './nutrition.css';
const labels={breakfast:'아침',lunch:'점심',dinner:'저녁',snack:'간식'};
export function useNutrition(){const {user,token}=useAuth();return useQuery({queryKey:['nutrition',user.id],queryFn:()=>api('/coach/nutrition',{token}),retry:false});}
function PreferencesForm({initial}){
 const {user,token}=useAuth(),cache=useQueryClient(),lock=useRef(false);const [form,setForm]=useState(initial||{goal:'balanced',allergies:'',avoid:'',preference:''}),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function save(e){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await api('/coach/nutrition',{token,method:'PUT',body:form});await cache.invalidateQueries({queryKey:['nutrition',user.id]});setNotice('식사 선호를 저장했어요. 다음 메시지부터 코치가 참고해요.');}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 return <form className="nutrition-preferences" onSubmit={save}><span className="section-eyebrow">MY FOOD ROUTINE</span><h3>어떤 식사를 하고 싶어요?</h3><p>본인만 볼 수 있어요. 저장한 선호는 메시지를 보낼 때 AI가 참고해요.</p><fieldset disabled={busy}><label>식사 목표<select value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}>{[['balanced','균형 잡힌 식사'],['fitness','체력 향상'],['muscle','근육 증가'],['weight','체중 관리']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{[['allergies','알레르기','없다면 ‘없음’, 있다면 땅콩·우유 등'],['avoid','피하고 싶은 음식','예: 생선, 매운 음식'],['preference','식사 선호·준비 여건','예: 채식 위주, 조리 15분, 외식이 잦아요']].map(([key,title,placeholder])=><label key={key}>{title}<input maxLength={300} value={form[key]} placeholder={placeholder} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button className="btn btn-ghost" disabled={busy}>{busy?'저장 중…':'식사 선호 저장'}</button></fieldset><p role="status">{notice}</p>{error&&<p role="alert">{error}</p>}</form>;
}
export function NutritionPreferences(){const query=useNutrition();if(query.isPending)return <p role="status">식사 선호를 불러오는 중…</p>;if(query.isError)return <p role="alert">식단 코치 설정을 불러오지 못했어요. <button onClick={()=>query.refetch()}>다시 시도</button></p>;return <PreferencesForm initial={query.data.preferences}/>;}
function Foods({plan}){return <><ul className="nutrition-foods">{plan.items.map((item,i)=><li key={i}><strong>{item.name}</strong><span>{item.amount}</span>{item.alternative&&<small>대체 아이디어 · {item.alternative}</small>}</li>)}</ul>{plan.note&&<p className="nutrition-note">{plan.note}</p>}<p className="nutrition-caution">AI가 제안한 구성으로, 영양성분을 검증한 식단은 아니에요. 알레르기가 있다면 제품의 원재료 표시도 확인해 주세요.</p></>;}
export function MealProposals({turn}){
 const query=useNutrition(),{user,token}=useAuth(),cache=useQueryClient(),lock=useRef(false);const [busy,setBusy]=useState(null),[error,setError]=useState('');
 async function save(position){if(lock.current)return;lock.current=true;setBusy(position);setError('');try{await api('/coach/meal-plans',{token,body:{turn_id:turn.id,position}});await cache.invalidateQueries({queryKey:['nutrition',user.id]});}catch(e){setError(e.message);}finally{lock.current=false;setBusy(null);}}
 if(!turn.meal_proposals?.length)return null;
 return <section className="nutrition-proposals"><h3>제안받은 식단</h3><p>마음에 드는 끼니를 계획으로 저장해 보세요.</p>{turn.meal_proposals.map((plan,position)=>{const saved=query.data?.plans.find(p=>p.turn_id===turn.id&&p.position===position);return <article className="nutrition-plan" key={position}><small>{plan.scheduled_on} · {labels[plan.meal_type]}</small><h4>{plan.title}</h4><Foods plan={plan}/>{saved?<p role="status">식단 계획에 저장했어요. <Link to={'/meals/new?plan='+saved.id}>먹은 식단으로 기록 ↗</Link></p>:<button className="btn btn-primary" disabled={busy!==null||!query.isSuccess} onClick={()=>save(position)}>{busy===position?'저장 중…':'식단 계획에 저장'}</button>}<Link className="nutrition-store" to={'/store?q='+encodeURIComponent(plan.items[0].name)}>스토어에서 식품 찾기 ↗</Link></article>;})}{error&&<p role="alert">{error}</p>}</section>;
}
export function SavedMealPlans(){const query=useNutrition(),{user,token}=useAuth(),cache=useQueryClient(),lock=useRef(false);const [confirm,setConfirm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');async function remove(id){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await api('/coach/meal-plans/'+id,{token,method:'DELETE'});await cache.invalidateQueries({queryKey:['nutrition',user.id]});setConfirm(null);}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 return <section className="nutrition-saved"><span className="section-eyebrow">MY MEAL PLAN</span><h2>저장한 식단 계획</h2><p className="muted small">최근 100개 · 계획을 지워도 먹은 기록은 유지돼요.</p>{query.isPending?<p role="status">식단 계획을 불러오는 중…</p>:query.isError?<p role="alert">계획을 불러오지 못했어요. <button onClick={()=>query.refetch()}>다시 시도</button></p>:!query.data.plans.length?<p className="coach-empty">코치가 제안한 끼니를 저장하면 여기에 모여요.</p>:query.data.plans.map(plan=><article key={plan.id}><small>{plan.scheduled_on} · {labels[plan.meal_type]}</small><h3>{plan.title}</h3><Foods plan={plan}/><Link to={'/meals/new?plan='+plan.id}>먹은 식단으로 기록 ↗</Link><Link to={'/store?q='+encodeURIComponent(plan.items[0].name)}>스토어에서 식품 찾기 ↗</Link>{confirm===plan.id?<div><p>이 식단 계획을 삭제할까요?</p><button disabled={busy} onClick={()=>remove(plan.id)}>삭제 확인</button><button disabled={busy} onClick={()=>setConfirm(null)}>취소</button></div>:<button className="coach-delete" onClick={()=>setConfirm(plan.id)}>계획 삭제</button>}</article>)}{error&&<p role="alert">{error}</p>}</section>;
}
