import {useRef,useState,useEffect} from 'react';
import {Link} from 'react-router';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useAuth} from '../auth/index.js';
import {api} from '../../shared/api.js';
import SportIcon from '../../shared/SportIcon.jsx';
import './partners.css';
const money=n=>n.toLocaleString('ko-KR')+'원';
const statusLabel={pending:'예약 요청 · 결제 전',test_paid:'결제 시뮬레이션 완료',cancelled:'취소 완료'};
export default function PartnersPage({embedded=false}){
 const {user,token}=useAuth(),cache=useQueryClient(),lock=useRef(false),pending=useRef(null);
 const catalog=useQuery({queryKey:['partners'],queryFn:()=>api('/partners',{token}),retry:false});
 const reservations=useQuery({queryKey:['partner-reservations',user.id],queryFn:()=>api('/partners/reservations',{token}),retry:false});
 const [selected,setSelected]=useState(null),[visit,setVisit]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState(null),[filter,setFilter]=useState('all');
 useEffect(()=>{if(!selected&&!confirm)return;const dialog=document.querySelector('.partner-sheet');const handler=e=>{if(e.key==='Escape'&&!lock.current){setSelected(null);setConfirm(null);}if(e.key==='Tab'){const items=[...dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),a[href]')];if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[selected,confirm]);
 const today=new Date(Date.now()+9*3600000).toISOString().slice(0,10),max=new Date(Date.now()+9*3600000+90*86400000).toISOString().slice(0,10);
 async function reserve(e){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');const key=selected.offer.id+visit;if(pending.current?.key!==key)pending.current={key,id:crypto.randomUUID()};
  try{await api('/partners/reservations',{token,body:{id:pending.current.id,offerId:selected.offer.id,visitOn:visit}});await cache.invalidateQueries({queryKey:['partner-reservations',user.id]});setSelected(null);pending.current=null;setNotice('데모 예약 요청을 저장했어요. 아래 내 예약에서 결제 흐름을 체험해 보세요.');}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}
 }
 async function change(row,action){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await api('/partners/reservations/'+row.id+'/'+action,{token,body:{}});await cache.invalidateQueries({queryKey:['partner-reservations',user.id]});setConfirm(null);setNotice(action==='simulate'?'결제 시뮬레이션을 완료했어요. 실제 청구나 시설 예약은 발생하지 않았어요.':'데모 예약을 취소했어요. 실제 결제·환불은 발생하지 않았어요.');}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 return <div className="partners-page">{!embedded&&<header className="page-head"><div><span className="section-eyebrow">MOVE TOGETHER</span><h1>운동할 곳 찾기</h1><p>관심이 생긴 운동, 가까운 공간에서 시작해 보세요.</p></div><Link to="/home">홈으로</Link></header>}
 <section className="partners-hero"><div><span className="partner-demo">제휴 서비스 미리보기</span><h2>나에게 맞는 공간.<br/>부담 없는 첫 운동.</h2><p>1일 이용권부터 체험 수업까지.<br/>운동을 시작하는 다음 한 걸음을 골라 보세요.</p><a href="#partner-reservations">내 예약 보기 ↓</a></div><div className="partner-hero-art" aria-hidden="true"><span>MOVE</span><SportIcon sport="gym"/><small>YOUR NEXT STEP</small></div></section>
 <div className="partner-disclosure"><strong>현재는 데모 시설과 예시 가격이에요.</strong><p>실제 제휴·예약 확정·결제는 이루어지지 않습니다. 결제 시뮬레이션에는 카드 정보를 입력하지 않아요.</p></div>
 <div className="partner-filters" aria-label="시설 종류">{[['all','전체'],['gym','헬스·PT'],['other','필라테스'],['running','러닝']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div>
 {catalog.isPending?<p role="status">운동 공간을 불러오고 있어요.</p>:catalog.isError?<p role="alert">공간을 불러오지 못했어요. <button onClick={()=>catalog.refetch()}>다시 시도</button></p>:<div className="partner-grid">{catalog.data.facilities.filter(f=>filter==='all'||filter===f.sport).map(f=><article className="partner-card" key={f.id}><div className={'partner-cover '+f.color}><span>DEMO SPACE {f.icon}</span><SportIcon sport={f.sport}/><strong>{f.tag}</strong></div><div className="partner-card-body"><small>{f.area} · 가상 시설</small><h2>{f.name}</h2><p>{f.description}</p><ul>{f.features.map(t=><li key={t}>{t}</li>)}</ul><div className="partner-offers">{f.offers.map(offer=><button key={offer.id} onClick={()=>{setSelected({facility:f,offer});setVisit(today);setError('');}}><span><strong>{offer.name}</strong><small>{offer.minutes}분 · 예시 이용권</small></span><b>{money(offer.amount)} <span aria-hidden="true">↗</span></b></button>)}</div></div></article>)}</div>}
 {notice&&<p className="partner-notice" role="status">{notice}</p>}{error&&<p className="partner-notice error" role="alert">{error}</p>}
 <section id="partner-reservations" className="partner-reservations"><header><h2>내 예약</h2><span>최근 100개 · 데모 예약</span></header>{reservations.isPending?<p role="status">예약을 불러오는 중…</p>:reservations.isError?<p role="alert">{reservations.error.message} <button onClick={()=>reservations.refetch()}>다시 시도</button></p>:!reservations.data.length?<div className="partner-empty"><strong>첫 운동을 계획해 볼까요?</strong><p>위에서 체험권을 고르면 이곳에 예약이 모여요.</p></div>:reservations.data.map(row=><article className="partner-reservation" key={row.id}><div><span className={'reservation-status '+row.status}>{statusLabel[row.status]}</span><h3>{row.facility_name} · {row.offer_name}</h3><p>{row.visit_on} 방문 희망 · {money(row.amount)} · 시뮬레이션</p><small>예약 번호 {row.id.slice(0,8)}</small></div><div className="reservation-actions">{row.status==='pending'&&<button className="btn btn-primary" onClick={()=>setConfirm({row,action:'simulate'})}>결제 흐름 체험</button>}{row.status!=='cancelled'&&<button className="btn btn-ghost" onClick={()=>setConfirm({row,action:'cancel'})}>예약 취소</button>}</div></article>)}</section>
 {selected&&<div className="partner-overlay"><section className="partner-sheet" role="dialog" aria-modal="true" aria-labelledby="reservation-title"><button className="partner-close" aria-label="예약 창 닫기" disabled={busy} onClick={()=>setSelected(null)}>×</button><span className="section-eyebrow">DEMO RESERVATION</span><h2 id="reservation-title">{selected.offer.name}</h2><p>{selected.facility.name} · {selected.offer.minutes}분</p><form onSubmit={reserve}><label>방문 희망일<input autoFocus type="date" required value={visit} min={today} max={max} onChange={e=>setVisit(e.target.value)}/></label><div className="partner-total"><span>예시 이용 금액</span><strong>{money(selected.offer.amount)}</strong></div><p className="muted small">시설로 전달되지 않는 데모 예약 요청이에요. 실제 방문 일시나 이용권이 확정되지 않습니다.</p>{error&&<p role="alert">{error}</p>}<button className="btn btn-primary btn-block" disabled={busy||!reservations.isSuccess}>{busy?'저장 중…':'데모 예약 요청 저장'}</button>{reservations.isError&&<p>예약 저장 설정이 필요해요.</p>}</form></section></div>}
 {confirm&&<div className="partner-overlay"><section className="partner-sheet" role="dialog" aria-modal="true" aria-labelledby="payment-title"><span className="section-eyebrow">{confirm.action==='simulate'?'PAYMENT SIMULATION':'CANCEL RESERVATION'}</span><h2 id="payment-title">{confirm.action==='simulate'?'결제 흐름을 체험할까요?':'데모 예약을 취소할까요?'}</h2><p>{confirm.row.facility_name}<br/>{confirm.row.offer_name} · {confirm.row.visit_on}</p><div className="partner-total"><span>예시 금액</span><strong>{money(confirm.row.amount)}</strong></div><p>실제 청구·환불·시설 예약은 발생하지 않아요.</p>{error&&<p role="alert">{error}</p>}<button autoFocus className="btn btn-primary btn-block" disabled={busy} onClick={()=>change(confirm.row,confirm.action)}>{busy?'처리 중…':confirm.action==='simulate'?'시뮬레이션 완료하기':'예약 취소 확인'}</button><button className="btn btn-ghost btn-block" disabled={busy} onClick={()=>setConfirm(null)}>돌아가기</button></section></div>}
 </div>;
}

