import { Link, Navigate } from 'react-router';
import { useAuth } from '../auth/index.js';
import SportIcon from '../../shared/SportIcon.jsx';
import { Wordmark } from '../../shared/AppShell.jsx';
import './introduction.css';
import { useIntroMotion } from './useIntroMotion.js';

function Brand(){return <Wordmark/>;}
function RecordPreview(){return <div className="intro-record"><div className="intro-card-top"><span>MY WEEK</span><span>기록 예시</span></div><h3>차곡차곡 쌓인 이번 주</h3><div className="intro-stats"><div><b>3<small>회</small></b><span>운동 횟수</span></div><div><b>12.4<small>km</small></b><span>총 거리</span></div><div><b>2:10</b><span>총 시간</span></div></div><div className="intro-bars" aria-label="월요일 40분, 수요일 35분, 토요일 55분 운동한 예시">{[40,0,35,0,0,55,0].map((v,i)=><div key={i}><span style={{height:`${v*1.6+4}px`}} data-active={v>0}/><small>{'월화수목금토일'[i]}</small></div>)}</div><div className="intro-record-line"><SportIcon sport="running"/><div><strong>강바람 따라 가볍게</strong><small>토요일 · 러닝</small></div><b>5.2 km</b></div></div>;}
function CoachPreview(){return <div className="intro-chat"><div className="intro-card-top"><strong>CrewFit 코치</strong><span>대화 기능 준비 중</span></div><p className="intro-message mine">이번 주는 바빠서, 짧게 운동하고 싶어.</p><span className="intro-author">CrewFit 코치 · 대화 예시</span><p className="intro-message">꾸준히 이어갈 수 있게 짧은 일정으로 나눠볼까요? 가능한 요일과 시간을 알려주세요.</p><p className="intro-message mine">화요일, 목요일 저녁에 20분 정도!</p><div className="intro-schedule"><span>운동 계획 예시</span><div><b>화</b><p><strong>가볍게 걷기</strong><small>오후 8:00 · 20분</small></p><span>↗</span></div><div><b>목</b><p><strong>편안하게 걷기</strong><small>오후 8:00 · 20분</small></p><span>↗</span></div><p className="intro-calendar-caption">계획 확인 → 구글 캘린더에 추가 <small>연동 준비 중</small></p></div></div>;}
export default function LandingPage({preview=false}){
 const {loading,session}=useAuth();
 const motionRef=useIntroMotion(!loading && (!session || preview));
 if(loading)return <div className="center">불러오는 중…</div>;
 if(session&&!preview)return <Navigate to="/home" replace/>;
 return <div className="intro" ref={motionRef}><div className="intro-progress" aria-hidden="true"/><a className="skip-link" href="#intro-main">본문으로 건너뛰기</a><header className="intro-nav intro-wrap"><Link to="/" aria-label="CrewFit 홈"><Brand/></Link><nav aria-label="소개 메뉴"><a href="#features">함께할 수 있는 일</a><a href="#how">이용 방법</a></nav><Link className="intro-login" to={session?'/home':'/login'}>{session?'내 홈으로':'로그인'} <span>↗</span></Link></header>
 <main id="intro-main"><section className="intro-hero intro-wrap"><div className="intro-giant" aria-hidden="true"><Brand/></div><span className="intro-eyebrow">YOUR PACE. OUR CREW.</span><h1>오늘의 운동이,<br/><em>내일도 이어지도록.</em></h1><p>기록으로 나를 알고, 크루와 함께 계속해요.<br/>나의 운동 생활이 모이는 곳, CrewFit.</p><div className="intro-actions"><Link className="intro-button primary" to={session?'/home':'/signup'}>{session?'내 기록 보러 가기':'CrewFit 시작하기'} <span>↗</span></Link><a className="intro-button secondary" href="#features">어떤 서비스인가요? ↓</a></div><p className="intro-existing">이미 함께하고 있다면 <Link to={session?'/home':'/login'}>{session?'내 홈으로':'로그인'}</Link></p></section>
 <section id="features" className="intro-features intro-wrap"><div className="intro-section-heading"><span className="intro-eyebrow">MADE FOR YOUR EVERYDAY</span><h2>운동 전부터, 운동이 끝난 뒤까지.</h2><p>한 번의 의욕보다 오래가는 일상을 만들어가요.</p></div><div className="intro-usecases" aria-label="서비스 활용 예시"><span>오늘 걸은 길 남기기</span><span>내 페이스 돌아보기</span><span>같이 운동할 크루 찾기</span><span>식단도 함께 기록하기</span></div>
 <div className="intro-feature-row"><div className="intro-copy"><span className="intro-index">01 / RECORD</span><h2>어제보다 얼마나?<br/>기록이 알려줄 거예요.</h2><p>러닝 경로부터 헬스 세트, 오늘 먹은 식사까지.<br/>흩어진 기록을 모아 나만의 변화를 확인해요.</p><ul><li>러닝·걷기·자전거·수영·헬스·기타 6종목</li><li>야외 운동 GPS 경로와 시간 기록</li><li>운동 목표와 주간 통계를 한눈에</li></ul><span className="intro-available">지금 이용할 수 있어요</span></div><RecordPreview/></div>
 <div className="intro-feature-row reverse"><div className="intro-copy"><span className="intro-index">02 / YOUR COACH</span><h2>내 기록을 이해하는,<br/>나의 운동 파트너.</h2><p>운동과 식단, 목표를 함께 돌아보는 AI 피드백.<br/>다음에는 대화로 계획을 만들고, 내 캘린더까지 이어가요.</p><ul><li>현재: 일·주·월 기록 기반 AI 피드백</li><li>준비 중: 대화형 코치와 운동 계획 저장</li><li>준비 중: 구글 로그인·캘린더 일정 등록</li></ul></div><CoachPreview/></div>
 <div className="intro-feature-row"><div className="intro-copy"><span className="intro-index">03 / BETTER TOGETHER</span><h2>속도는 달라도,<br/>함께하는 마음은 같으니까.</h2><p>종목, 지역, 운동하는 요일로 나에게 맞는 크루를 찾아요. 오늘의 성취를 나누면 다음 운동도 조금 쉬워져요.</p><ul><li>내 생활에 맞는 크루 찾기</li><li>크루 피드에 운동 기록과 사진 공유</li><li>준비 중: 크루 단체 채팅과 1:1 대화</li></ul></div><div className="intro-crew"><div className="intro-card-top"><span>OUR CREW</span><span>크루·게시글 예시</span></div><div className="intro-crew-banner"><span>↗</span><small>러닝 크루 · 서울 마포구</small><h3>한강 모닝 러너스</h3><p>빠르게보다, 오래 함께 달려요.</p></div><div className="intro-person"><span>서</span><div><small>작성자</small><strong>서연</strong></div><small>오늘 오전 8:40</small></div><p>오늘은 바람이 좋아서 조금 더 달렸어요.<br/>함께해 준 크루원들 덕분에 기분 좋은 시작 🌿</p><div className="intro-run-chip"><SportIcon sport="running"/><strong>아침 러닝</strong><span>5.2 km · 32분</span></div><div className="intro-reaction">♡ 좋아요 8 <span>댓글 3</span></div></div></div></section>
 <section className="intro-next intro-wrap"><span className="intro-eyebrow">WHAT’S NEXT</span><h2>운동 밖의 선택도,<br/>조금 더 가볍게.</h2><p>식단에 맞는 식사 제안부터 필요한 상품을 찾는 일까지.<br/>CrewFit이 함께할 다음 일상을 준비하고 있어요.</p><div className="intro-next-grid"><article><span>01 · 준비 중</span><h3>내 생활에 맞는 식단</h3><p>취향과 예산, 식품 제한 사항을 반영한 식사 제안.</p></article><article><span>02 · 준비 중</span><h3>선택에서 구매까지</h3><p>상품 후보를 비교하고 판매처에서 직접 구매하는 연결.</p></article></div></section>
 <section id="how" className="intro-how intro-wrap"><span className="intro-eyebrow">START SMALL, KEEP GOING</span><h2>시작은 가볍게 해도 괜찮아요.</h2><ol><li><b>1</b><h3>나를 알려주세요</h3><p>가입하고 좋아하는 종목과 활동 지역을 설정해요.</p></li><li><b>2</b><h3>오늘을 남겨보세요</h3><p>짧은 산책도 좋아요. 운동과 식단을 내 기록으로 쌓아요.</p></li><li><b>3</b><h3>함께 이어가세요</h3><p>AI 피드백으로 돌아보고 크루와 작은 성취를 나눠요.</p></li></ol></section>
 <section className="intro-faq intro-wrap"><h2>궁금할 수 있는 것들</h2><article><h3>앱을 설치해야 하나요?</h3><p>휴대폰과 컴퓨터 브라우저에서 이용할 수 있어요. GPS 측정 중에는 화면과 기록 탭을 켜 두어야 해요.</p></article><article><h3>소개된 기능을 모두 사용할 수 있나요?</h3><p>기록·식단·목표·AI 피드백·크루·피드는 지금 이용할 수 있어요. 대화형 코치, 구글 연동, 채팅, 상품 연결은 준비 중이에요. 페이지의 기록과 대화는 설명을 위한 예시예요.</p></article></section>
 <section className="intro-final intro-wrap"><span>LET’S MOVE, TOGETHER.</span><h2>오늘의 나부터,<br/>함께 시작해요.</h2><Link className="intro-button" to={session?'/home':'/signup'}>{session?'내 홈으로 가기':'CrewFit 시작하기'} ↗</Link></section></main><footer className="intro-footer intro-wrap"><Brand/><p>나의 페이스, 우리의 크루.</p><Link to={session?'/home':'/login'}>{session?'내 홈':'로그인'}</Link><small>© 2026 CrewFit · 캡스톤 프로젝트</small></footer></div>;
}


